version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: url
    ports:
      - "3306:3306"